# Site
title:              ~$ reverseshell
bio:                '[+] Connection established.'
description:        "Pythons, otimização matemática e segurança digital."
locale:             pt_br
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reverseshell.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   reverseshell


# Social
analytics-id:       "default"
twitter:            carlosfab
facebook:           default
instagram:          default
github:             carlosfab

# personal
location:           São José dos Campos
phone:              310-318-5555
email:              carlos@reverseshell.io

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
